---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: data services, data protection, data mobility, backup, replication, netapp console 
summary: Découvrez comment utiliser NetApp Backup and Recovery dans le déploiement local de NetApp Console pour protéger et gérer vos données. 
---
= Découvrez NetApp Backup and Recovery dans le déploiement local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery est un service de données qui offre une protection des données efficace, sécurisée et économique pour toutes vos charges de travail ONTAP, y compris les volumes, les bases de données, les machines virtuelles et les charges de travail Kubernetes.

Une charge de travail est un regroupement logique de ressources au sein d'un système, géré comme une unité unique à des fins de protection, de gouvernance, de détection et de restauration. Dans Backup and Recovery, une charge de travail est l'unité que vous protégez. Sa signification dépend de la source de données : pour Kubernetes, une charge de travail est une application ; pour les environnements de machines virtuelles, c'est une machine virtuelle ; et pour les environnements de bases de données, c'est une base de données.

La prise en charge de la sauvegarde et de la restauration est déjà intégrée à tous les systèmes ONTAP, il n’est donc pas nécessaire d’ajouter du matériel ou des passerelles de média supplémentaires. Cela rend les opérations de sauvegarde simples et rentables. La NetApp Console simplifie la mise en œuvre de toute stratégie de sauvegarde, y compris l’ensemble des variantes de sauvegarde 3-2-1, sans avoir besoin de plusieurs gestionnaires de ressources ou de personnel spécialisé.


NOTE: NetApp Backup and Recovery est en mode préversion pour le déploiement local de NetApp Console. Le service n'est pas encore disponible de manière générale, et les fonctionnalités sont susceptibles d'évoluer.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Apprenez-en davantage sur NetApp Backup and Recovery."^].
