---
sidebar: sidebar 
permalink: reference-local-known-limitations.html 
keywords: console local deployment, known limitations, unsupported platforms, unsupported devices, unsupported functions, IP range 
summary: Référence pour les limitations connues dans le déploiement local de NetApp Console. 
---
= Limitations connues du déploiement local de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues désignent les plateformes, les périphériques ou les fonctions non pris en charge par cette version du produit, ou qui ne fonctionnent pas correctement avec celle-ci. Examinez attentivement ces limitations.



[[console-vm-limitations]]
== Limites de la machine virtuelle Console



[[possible-conflict-with-ip-addresses-in-the-10-42-0-016-and-10-43-0-016-ranges]]
=== Conflit possible avec les adresses IP des plages 10.42.0.0/16 et 10.43.0.0/16

NetApp Console local deployment utilise un espace d'adressage fixe pour la communication inter-services. Les plages d'adresses IP 10.42.0.0/16 et 10.43.0.0/16 sont utilisées pour le réseau interne. Avant de déployer Console local deployment, assurez-vous que ces plages d'adresses IP ne sont pas attribuées à d'autres machines virtuelles, plages DHCP, enregistrements DNS ou pools VIP d'équilibreur de charge sur les VLANs mis à disposition pour Console local deployment.

Consultez l'article de la base de connaissances Agent IP conflict with existing network pour obtenir des instructions sur la façon de modifier l'adresse IP des interfaces de l'agent.



[[shared-linux-hosts-are-not-supported]]
=== Les hôtes Linux partagés ne sont pas pris en charge

NetApp Console le déploiement local n'est pas pris en charge sur une machine virtuelle partagée avec d'autres applications. La machine virtuelle doit être dédiée au déploiement local de NetApp Console.



[[third-party-agents-and-extensions]]
=== Agents et extensions tiers

Les agents tiers ou les extensions de machine virtuelle ne sont pas pris en charge sur la machine virtuelle de déploiement local de la NetApp Console.



[[identity-and-access-limitations]]
== Limitations d'identité et d'accès

[cols="1,3"]
|===
| Zone | Limitation 


| Intégration des utilisateurs locaux et récupération des comptes | Un serveur de messagerie SMTP doit être configuré avant que vous puissiez inviter des utilisateurs locaux ou utiliser la réinitialisation de mot de passe pour les utilisateurs locaux. 


| Intégration Active Directory | L'utilisation d'adresses électroniques en double n'est pas prise en charge entre les utilisateurs locaux et les utilisateurs Active Directory. Par exemple, si l'administrateur local initial de l'organisation s'ajoute ultérieurement en tant qu'utilisateur Active Directory, il doit utiliser une adresse électronique différente. 
|===