---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: 'NetApp propose une assistance pour le déploiement local de NetApp Console de différentes manières. De nombreuses options d’assistance en libre-service gratuites sont disponibles 24h/24 et 7j/7, telles que des articles de la base de connaissances (KB) et un forum communautaire. Votre inscription à l’assistance inclut un support technique à distance via un système de tickets web.' 
---
= Obtenez de l'aide concernant le déploiement local de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp propose une assistance pour le déploiement local de NetApp Console de différentes manières. De nombreuses options d’assistance en libre-service gratuites sont disponibles 24h/24 et 7j/7, telles que des articles de la base de connaissances (KB) et un forum communautaire. Vous pouvez vous inscrire pour obtenir de l’assistance avec le numéro de série de toute ressource de stockage associée au déploiement local de NetApp Console. L’inscription inclut une assistance technique à distance via un système de tickets web.



[[use-self-support-options]]
== Utilisez les options d'auto-assistance

Ces options sont disponibles gratuitement, 24 heures sur 24, 7 jours sur 7 :

* Documentation
+
La documentation relative au déploiement local de la NetApp Console que vous consultez actuellement.

* https://kb.netapp.com/Cloud/BlueXP["Base de connaissances"^]
+
Recherchez dans la base de connaissances NetApp des articles qui vous aident à résoudre des problèmes.





[[open-a-support-case-with-netapp-console-local-deployment]]
== Ouvrez un ticket de support avec le déploiement local de NetApp Console

Ouvrez un ticket d'assistance en utilisant l'un des numéros de série du système de stockage NetApp gérés via votre environnement de déploiement local NetApp Console.

.Étapes
. Rendez-vous sur  https://mysupport.netapp.com["Site de support NetApp"^] et connectez-vous avec vos identifiants d’assistance NetApp.
. Sélectionnez *Cases and Parts > Create Technical Case*.
. Saisissez le numéro de série du système de stockage NetApp associé au produit de déploiement local de la Console rencontrant ce problème.
. Créez un nouveau dossier et sélectionnez le code de catégorie approprié pour le déploiement local de la NetApp Console.




[[download-a-support-bundle]]
== Téléchargez un bundle de support

Un pack de support contient les journaux récents et les informations de configuration. Vous pouvez télécharger le pack le plus récent et l'envoyer au support technique de NetApp si cela vous est demandé.

.Étapes
. Sélectionnez *Administration > Support* pour afficher la page Support.
. Sur la carte Support, sélectionnez *Créer* pour créer un ensemble de journaux et de données de configuration.
. Une fois le bundle créé, sélectionnez *Télécharger*. Vous êtes invité à télécharger un fichier ZIP.
+
Le système ne conserve qu'un seul bundle à la fois. La création d'un nouveau support bundle remplace le précédent.


