---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: 'Vous pouvez auditer l"activité des utilisateurs (initiée depuis l"interface utilisateur et l"API) depuis la page Audit, et vous pouvez surveiller l"état des opérations que la Console effectue afin de vérifier s"il existe des problèmes que vous devez résoudre. Vous pouvez consulter l"état depuis la page Audit ou configurer l"envoi du journal des audits vers votre propre serveur syslog.' 
---
= Audit de l'activité de déploiement local de la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Documentez l'activité administrative lors des contrôles de conformité afin de vérifier les modifications d'accès et de conserver un historique des actions sur le déploiement local de NetApp Console.

.Rôles requis
Super administrateur, administrateur d'organisation, administrateur de dossiers et de flottes, analyste de support opérationnel, super visionneur, visionneur d'organisation ou visionneur de dossiers et de flottes. link:reference-iam-predefined-roles.html["Découvrez les rôles d'accès"].

Vous pouvez consulter l'activité d'audit dans le déploiement local de la NetApp Console et télécharger un fichier CSV du journal des audits.



[[audit-user-activity-from-the-audit-page]]
== Audit de l'activité des utilisateurs depuis la page d'audit

Surveillez l'activité administrative pour suivre les modifications apportées à votre déploiement local NetApp Console lors de la résolution d'incidents ou de la vérification des responsabilités opérationnelles.

La page Audit affiche les actions effectuées par les utilisateurs au sein de votre organisation. Par exemple, vous pouvez vérifier qui a ajouté un membre à une organisation, confirmer qu’un utilisateur a supprimé une flotte, ou consulter d’autres actions de gestion du stockage effectuées par les utilisateurs dans votre organisation.

Les journaux des audits indiquent une activité pour les services suivants :

* Tenancy : actions liées à la gestion de votre organisation, telles que l’ajout d’utilisateurs, la création de flottes et l’association de ressources.
* Gestion du stockage : actions liées à la gestion de vos ressources de stockage.
* Fédération : actions liées à la gestion des fédérations, telles que la création de fédérations et l'ajout ou la suppression d'organisations fédérées.


.Étapes
. Sélectionnez *Administration > Audit*.
. Utilisez les filtres situés au-dessus du tableau pour affiner l'activité d'audit par plage horaire, service, action, ressource, utilisateur ou statut.


Les entrées d'audit indiquent l'utilisateur ayant effectué l'action lorsque son identité peut être établie. Si l'identité de l'utilisateur ne peut être établie, l'entrée affiche l'identifiant de l'utilisateur `auth0Id` au lieu de son nom.

Par exemple, vous pouvez utiliser le filtre *Service* pour afficher les actions liées à un service spécifique, ou vous pouvez utiliser le filtre *Utilisateur* pour afficher les actions liées à un compte utilisateur spécifique.



[[filter-audit-logs-for-identity-and-access-management-actions]]
=== Filtrer les journaux des audits pour les actions de gestion des identités et de gestion des accès

Examinez les modifications apportées à la gestion des accès afin de confirmer qui a modifié les ressources de l'organisation et de soutenir des enquêtes de sécurité précises.

.Étapes
. Sélectionnez *Administration > Audit*.
. Utilisez les filtres pour affiner les résultats. Sélectionnez *Service* puis *Tenancy*.
. Utilisez les autres filtres pour affiner davantage les résultats.
+
Par exemple, utilisez le filtre *Utilisateur* pour afficher les actions IAM effectuées par un compte utilisateur spécifique.





[[download-audit-logs-from-the-audit-page]]
=== Téléchargez les journaux des audits depuis la page Audit

Conservez un enregistrement indépendant des actions de l'organisation afin de faciliter les audits de conformité et les futures enquêtes sur les incidents. Le fichier CSV téléchargé contient toutes les colonnes du journal des audits, même si vous appliquez des filtres ou modifiez les colonnes affichées.

.Étapes
. Sur la page *Audit*, sélectionnez l'icône de téléchargement dans le coin supérieur droit du tableau.

