= 
:allow-uri-read: 


Après avoir installé et configuré l'agent Console, ajoutez vos identifiants cloud afin que l'agent Console dispose des autorisations requises pour effectuer des actions dans AWS ou Azure.

[role="tabbed-block"]
====
.AWS
--
.Avant de commencer
Si vous venez de créer ces identifiants AWS, leur disponibilité peut prendre quelques minutes. Veuillez patienter quelques minutes avant d'ajouter les identifiants à la NetApp Console.

.Étapes
. Sélectionnez *Administration > Identifiants*.
. Sélectionnez *identifiants de l'organisation*.
. Sélectionnez *Add Credentials* et suivez les étapes de l'assistant.
+
.. *Emplacement des identifiants* : Sélectionnez *Amazon Web Services > Agent*.
.. *Définir les identifiants* : Saisissez une clé d'accès AWS et une clé secrète.
.. *Abonnement Marketplace* : Associez un abonnement Marketplace à ces identifiants cloud en vous abonnant maintenant ou en sélectionnant un abonnement existant.
.. *Vérification* : Confirmez les détails concernant les nouveaux identifiants cloud et sélectionnez *Ajouter*.




Vous pouvez maintenant aller à la  https://console.netapp.com["NetApp Console"^] pour commencer à utiliser l’agent Console.

--
.Azure
--
.Avant de commencer
Si vous venez de créer ces identifiants Azure, ils peuvent prendre quelques minutes avant d'être disponibles. Attendez quelques minutes avant d'ajouter les identifiants à l'agent NetApp Console.

.Étapes
. Sélectionnez *Administration > Identifiants*.
. Sélectionnez *Add Credentials* et suivez les étapes de l'assistant.
+
.. *Emplacement des identifiants* : Sélectionnez *Microsoft Azure > Agent*.
.. *Définir les identifiants* : Saisissez les informations relatives au principal de service Microsoft Entra qui accorde les autorisations requises :
+
*** ID de l'application (client)
*** ID de répertoire (tenant)
*** Secret du client


.. *Abonnement Marketplace* : Associez un abonnement Marketplace à ces identifiants cloud en vous abonnant maintenant ou en sélectionnant un abonnement existant.
.. *Vérification* : Confirmez les détails concernant les nouveaux identifiants cloud et sélectionnez *Ajouter*.




.Résultat
L’agent de Console dispose désormais des autorisations nécessaires pour effectuer des actions dans Azure en votre nom. Vous pouvez maintenant accéder à la  https://console.netapp.com["NetApp Console"^] pour commencer à utiliser l’agent de Console.

--
====