= 
:allow-uri-read: 


Créez un rôle et appliquez-le à un compte de service que vous utiliserez pour l'instance de machine virtuelle de l'agent NetApp Console.

.Étapes
. Créer un rôle personnalisé dans Google Cloud :
+
.. Créez un fichier YAML qui inclut les autorisations définies dans le link:reference-permissions-gcp.html["Stratégie d'agent de console pour Google Cloud"].
.. Depuis Google Cloud, activez cloud shell.
.. Téléversez le fichier YAML qui inclut les autorisations requises pour l’agent de la Console.
.. Créez un rôle personnalisé à l'aide de la  `gcloud iam roles create` commande.
+
L'exemple suivant crée un rôle nommé « connector » au niveau du projet :

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs : Création et gestion de rôles personnalisés"^]



. Créez un compte de service dans Google Cloud :
+
.. Dans le service IAM & Admin, sélectionnez *Service Accounts > Create Service Account*.
.. Saisissez les informations du compte de service et sélectionnez *Créer et continuer*.
.. Sélectionnez le rôle que vous venez de créer.
.. Terminez les étapes restantes pour créer le rôle.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documentation Google Cloud : Création d’un compte de service"^]





.Résultat
Vous disposez désormais d'un compte de service que vous pouvez attribuer à l'instance de machine virtuelle de l'agent Console.
