= 
:allow-uri-read: 


.Avant de commencer
Vous devriez avoir les éléments suivants :

* Privilèges root pour installer l'agent Console.
* Détails concernant un serveur proxy, si un proxy est requis pour l'accès à Internet depuis l'agent Console.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite le redémarrage de l'agent Console.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy intercepteur.



NOTE: Il est impossible de configurer un certificat pour un serveur proxy transparent lors de l'installation manuelle de l'agent Console. Si vous devez configurer un certificat pour un serveur proxy transparent, vous devez utiliser la Maintenance Console après l'installation. En savoir plus sur le link:reference-agent-maint-console.html["Console de maintenance des agents"].

.À propos de cette tâche
Le programme d'installation disponible sur le site d'assistance NetApp peut être une version antérieure. Après l'installation, l'agent Console se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échoue.

. Téléchargez le logiciel agent Console depuis le https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^], puis copiez-le sur l’hôte Linux.
+
Vous devez télécharger le programme d'installation de l'agent « online » conçu pour être utilisé sur votre réseau ou dans le cloud.

. Attribuez les autorisations nécessaires à l'exécution du script.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Où <version> est la version de l’agent Console que vous avez téléchargée.

. Si vous effectuez l'installation dans un environnement Government Cloud, désactivez les vérifications de configuration. link:task-troubleshoot-console-local.html#disable-config-check["Découvrez comment désactiver les vérifications de configuration pour les installations manuelles."]
. Exécutez le script d'installation.
+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Vous devrez ajouter les informations de proxy si votre réseau nécessite un proxy pour accéder à Internet. Vous pouvez ajouter un proxy transparent ou explicite. Les paramètres --proxy et --cacert sont facultatifs et il ne vous sera pas demandé de les ajouter. Si vous avez un serveur proxy, vous devrez saisir les paramètres comme indiqué.

+
Voici un exemple de configuration d'un serveur proxy explicite avec un certificat signé par une autorité de certification :

+
[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy` configure l'agent de la Console pour utiliser un serveur proxy HTTP ou HTTPS en utilisant l'un des formats suivants :

+
** \http://adresse:port
** http://nom-utilisateur:mot-de-passe@adresse:port
** \http://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port
** https://adresse:port
** \https://nom-utilisateur:mot-de-passe@adresse:port
** \https://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port
+
Remarque :

+
*** L'utilisateur peut être un utilisateur local ou un utilisateur de domaine.
*** Pour un utilisateur de domaine, vous devez utiliser le code ASCII pour un \ comme indiqué ci-dessus.
*** L'agent Console ne prend pas en charge les noms d'utilisateur ou les mots de passe contenant le caractère @.
*** Si le mot de passe contient l'un des caractères spéciaux suivants, vous devez l'échapper en le faisant précéder d'une barre oblique inverse : & ou !
+
Par exemple :

+
\http://bxpproxyuser:netapp1\!@address:3128







`--cacert`Spécifie un certificat signé par une autorité de certification à utiliser pour l'accès HTTPS entre l'agent Console et le serveur proxy. Ce paramètre est obligatoire pour les serveurs proxy HTTPS, les serveurs proxy d'interception et les serveurs proxy transparents.

Voici un exemple de configuration d'un serveur proxy transparent. Lorsque vous configurez un proxy transparent, il n'est pas nécessaire de définir le serveur proxy. Vous devez simplement ajouter un certificat signé par une autorité de certification à l'hôte de votre agent Console.

+

[source, cli]
----
 ./NetApp_Console_Agent_Cloud_v4.0.0 --cacert /tmp/cacert/certificate.cer
----
. Si vous avez utilisé Podman, vous devrez ajuster le port aardvark-dns.
+
.. SSH vers la machine virtuelle de l'agent Console.
.. Ouvrez le fichier podman _/usr/share/containers/containers.conf_ et modifiez le port choisi pour le service DNS Aardvark. Par exemple, changez-le en 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Redémarrez la machine virtuelle de l’agent NetApp Console.




. Attendez la fin de l'installation.
+
À la fin de l'installation, le service de l'agent de console (occm) redémarre deux fois si vous avez spécifié un serveur proxy.




NOTE: En cas d'échec de l'installation, vous pouvez consulter le rapport d'installation et les journaux pour vous aider à résoudre les problèmes. link:task-troubleshoot-console-local.html#troubleshoot-installation["Découvrez comment résoudre les problèmes d'installation."]

. Ouvrez un navigateur Web depuis un hôte connecté à la machine virtuelle de l'agent Console et saisissez l'URL suivante :
+
https://_ipaddress_[]

. Après vous être connecté, configurez l'agent Console :
+
.. Spécifiez l'organisation à associer à l'agent de la Console.
.. Saisissez un nom pour le système.
.. Sous *Exécutez-vous dans un environnement sécurisé ?*, laissez le mode restreint désactivé.
+
Vous devez laisser le mode restreint désactivé, car ces étapes décrivent comment utiliser la Console en mode standard. Vous ne devez activer le mode restreint que si vous disposez d'un environnement sécurisé et que vous souhaitez déconnecter ce compte des services backend. Dans ce cas, link:task-quick-start-restricted-mode.html["Suivez les étapes pour commencer avec la NetApp Console en mode restreint"].

.. Sélectionnez *Let's start*.



