= 
:allow-uri-read: 


.Avant de commencer
Vous devriez avoir les éléments suivants :

* Privilèges root pour installer l'agent.
* Détails concernant un serveur proxy, si un proxy est requis pour l'accès à Internet depuis l'agent.
+
Vous avez la possibilité de configurer un serveur proxy après l'installation, mais cela nécessite de redémarrer l'agent.

* Un certificat signé par une autorité de certification, si le serveur proxy utilise HTTPS ou si le proxy est un proxy intercepteur.


.À propos de cette tâche
Le programme d'installation disponible sur le site d'assistance NetApp peut être une version antérieure. Après l'installation, l'agent se met automatiquement à jour si une nouvelle version est disponible.

.Étapes
. Si les variables système _http_proxy_ ou _https_proxy_ sont définies sur l'hôte, supprimez-les :
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Si vous ne supprimez pas ces variables système, l'installation échouera.

. Téléchargez le logiciel agent depuis le https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de support NetApp"^], puis copiez-le sur l’hôte Linux.
+
Vous devez télécharger le programme d'installation de l'agent « online » conçu pour être utilisé sur votre réseau ou dans le cloud.

. Attribuez les autorisations nécessaires à l'exécution du script.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Où <version> est la version de l’agent que vous avez téléchargée.

. Exécutez le script d'installation.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Les paramètres --proxy et --cacert sont facultatifs. Si vous avez un serveur proxy, vous devrez saisir les paramètres comme indiqué. Le programme d'installation ne vous invite pas à fournir des informations sur un proxy.

+
Voici un exemple de la commande utilisant les deux paramètres optionnels :

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configure l’agent pour utiliser un serveur proxy HTTP ou HTTPS selon l’un des formats suivants :

+
** \http://adresse:port
** http://nom-utilisateur:mot-de-passe@adresse:port
** \http://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port
** https://adresse:port
** \https://nom-utilisateur:mot-de-passe@adresse:port
** \https://nom-de-domaine%92nom-utilisateur:mot-de-passe@adresse:port
+
Remarque :

+
*** L'utilisateur peut être un utilisateur local ou un utilisateur de domaine.
*** Pour un utilisateur de domaine, vous devez utiliser le code ASCII pour un \ comme indiqué ci-dessus.
*** L'agent ne prend pas en charge les noms d'utilisateur ni les mots de passe contenant le caractère @.
*** Si le mot de passe contient l'un des caractères spéciaux suivants, vous devez l'échapper en le faisant précéder d'une barre oblique inverse : & ou !
+
Par exemple :

+
\http://bxpproxyuser:netapp1\!@address:3128





+
L'option --cacert spécifie un certificat signé par une autorité de certification à utiliser pour l'accès HTTPS entre l'agent et le serveur proxy. Ce paramètre est requis uniquement si vous spécifiez un serveur proxy HTTPS ou si le proxy est un proxy d'interception.

. Si vous avez utilisé Podman, vous devrez ajuster le port aardvark-dns.
+
.. Connectez-vous en SSH à la machine virtuelle de l'agent.
.. Ouvrez le fichier podman _/usr/share/containers/containers.conf_ et modifiez le port choisi pour le service DNS Aardvark. Par exemple, changez-le en 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Redémarrez la machine virtuelle de l'agent.




. Attendez la fin de l'installation.
+
À la fin de l'installation, le service agent (occm) redémarre deux fois si vous avez spécifié un serveur proxy.

. Ouvrez un navigateur Web depuis un hôte qui a une connexion à la machine virtuelle de l'agent et saisissez l'URL suivante :
+
https://_ipaddress_[]

. Après vous être connecté, configurez l'agent :
+
.. Spécifiez l'organisation NetApp Console à associer à l'agent.
.. Saisissez un nom pour le système.
.. Sous *Exécutez-vous dans un environnement sécurisé ?*, laissez le mode restreint désactivé.
+
Vous devez laisser le mode restreint désactivé, car ces étapes décrivent comment utiliser la Console en mode standard. Vous ne devez activer le mode restreint que si vous disposez d'un environnement sécurisé et que vous souhaitez déconnecter ce compte des services backend de la Console. Dans ce cas, link:task-quick-start-restricted-mode.html["Suivez les étapes pour commencer avec la NetApp Console en mode restreint"].

.. Sélectionnez *Let's start*.



